name: Push to dev environment

on:
  push:
    branches-ignore:
      - master
      - main
      - '*cd*'
      - '*ci*' # Ignore CICD branches

# This workflow will build a docker container, publish it to our private registry
# tagged as latest and with latest commit hash (shortened)
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone project
      uses: actions/checkout@v3

    - name: Get short commit hash
      id: variables
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest
        
    - name: "Login to private registry at: ${{ vars.DOCKER_REGISTRY_HOST }}"
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ vars.DOCKER_REGISTRY_HOST }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Build and push Docker image ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront
      run: |
        docker build . -t ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront:${{ steps.variables.outputs.sha }} -t ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront:latest

        docker push ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront:${{ steps.variables.outputs.sha }}
        docker push ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront:latest


    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v4.0.0
    #   with:
    #     allow: security.insecure # Activated because docker does not like self signed certificates
    #     push: true
    #     tags: ${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront:${{ steps.variables.outputs.sha }},${{ vars.DOCKER_REGISTRY_HOST }}/rfr/relfinderreformedfront:latest
