name: Release

on:
  push:
    tags: 
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup node js
      uses: actions/setup-node@v3.2.0
      
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        
    - name: Cache
      uses: actions/cache@v3.0.2
      with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

    - run: npm ci --ignore-scripts
    - run: npm run build --if-present
    - run: npm test

    - name: Set Versions
      uses: actions/github-script@v4
      id: set_version
      with:
        script: |
          const tag = context.ref.substring(10)
          const no_v = tag.replace('v', '')
          core.setOutput('no_v', no_v)

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3.1.1
      with:
        push: true
        tags: ghcr.io/woodenmaiden/relfinderreformedfront:${{ steps.set_version.outputs.no_v }},ghcr.io/woodenmaiden/relfinderreformedfront:latest
